# Generated by Django 5.2.7 on 2025-10-06 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('boundary_geojson', models.TextField(blank=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL)),
                ('sub_users', models.ManyToManyField(blank=True, related_name='assigned_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
