# Generated by Django 5.2.7 on 2025-10-06 06:27

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_maps_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
